---
- name: Set OS family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags: always

- name: Set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  tags: always

- name: install apache tomcat
  package:
    name: "{{ tomcat_package_name }}"
    state: present

#- name: start and enable tomcat
#  service:
#    name: "{{ tomcat_package_name }}"
#    state: started
#    enabled: true

- name: change permissions of tomcat configuration-files
  file:
    path: "{{ item }}"
    owner: "tomcat"
    group: "tomcat"
    mode: "0640"
  loop:
    - "/etc/tomcat/server.xml"
    - "/etc/tomcat/context.xml"
    - "/etc/tomcat/web.xml"
    - "/etc/tomcat/tomcat-users.xml"
- name: change permissions of tomcat-directories
  file:
    path: "{{ item }}"
    owner: "tomcat"
    group: "tomcat"
    mode: "0750"
  loop:
    - "/usr/share/tomcat/"
    - "/usr/share/tomcat/conf/"
    - "/etc/tomcat"
    - "/var/cache/tomcat"
    - "/var/log/tomcat"
    - "/var/lib/tomcat"
